spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sihwa
    username: sa
    password:
    driver-class-name: org.h2.Driver

jwt:
  secretKey: S3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3y
  refreshKey: S3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3yS3cr3tK3y